apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2020-11-22T22:59:56Z"
  generation: 1
  labels:
    app: group8-app
  name: group8-app
  namespace: default
  resourceVersion: "7798"
  selfLink: /apis/apps/v1/namespaces/default/deployments/group8-app
  uid: b5c39de1-348b-4c8e-9c05-43b2b7af3776
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: group8-app
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: group8-app
    spec:
      containers:
      - image: gcr.io/cloud-com-294113/github.com/mahmad-lu/cloud_group_8:89b7f96
        imagePullPolicy: IfNotPresent
        name: cloud-group-8-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2020-11-22T23:00:16Z"
    lastUpdateTime: "2020-11-22T23:00:16Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2020-11-22T22:59:56Z"
    lastUpdateTime: "2020-11-22T23:00:16Z"
    message: ReplicaSet "group8-app-7d487dc465" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 3
  replicas: 3
  updatedReplicas: 3
